import ast
import os
import sys
import time
import shutil
import subprocess
import tempfile
import traceback
from pathlib import Path
from typing import Any, Optional


SCENE_BASES = {
    "Scene",
    "MovingCameraScene",
    "ThreeDScene",
    "ZoomedScene",
}

QUALITY_FLAGS = {"ql", "qm", "qh", "qk"}


def is_inside_skill_install_dir(path: Path) -> bool:
    resolved = path.resolve()
    parts = [part.lower() for part in resolved.parts]

    for index, part in enumerate(parts[:-1]):
        if part in {".codex", ".opencode"} and parts[index + 1] == "skills":
            return True

    return False


def command_works(command: list[str]) -> bool:
    try:
        probe = subprocess.run(
            [*command, "--version"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=10,
        )
    except Exception:
        return False

    return probe.returncode == 0


def windows_user_manim_candidates() -> list[str]:
    local_app_data = os.environ.get("LOCALAPPDATA")
    if not local_app_data:
        return []

    programs_dir = Path(local_app_data) / "Programs" / "Python"
    candidates = []

    try:
        if programs_dir.exists():
            candidates.extend(
                str(path)
                for path in sorted(programs_dir.glob("Python*/Scripts/manim.exe"), reverse=True)
                if path.is_file()
            )
    except OSError:
        pass

    for version in ("313", "312", "311", "310", "39", "38"):
        candidate = programs_dir / f"Python{version}" / "Scripts" / "manim.exe"
        candidates.append(str(candidate))

    return list(dict.fromkeys(candidates))


def manim_command_base() -> list[str]:
    python_module_command = [sys.executable, "-m", "manim"]
    if command_works(python_module_command):
        return python_module_command

    manim_exe = shutil.which("manim")
    candidates = [manim_exe] if manim_exe else []
    candidates.extend(windows_user_manim_candidates())

    for candidate in candidates:
        command = [candidate]
        if command_works(command):
            return command

    return python_module_command


def parse_command(command: Optional[str]) -> Optional[list[str]]:
    if command is None:
        return None

    import shlex

    return shlex.split(command, posix=False)


def detect_scene_name(code: str, default: str = "GeneratedScene") -> str:
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return default

    first_scene = None

    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue

        if node.name == default:
            return default

        for base in node.bases:
            base_name = None

            if isinstance(base, ast.Name):
                base_name = base.id
            elif isinstance(base, ast.Attribute):
                base_name = base.attr

            if base_name in SCENE_BASES:
                first_scene = node.name
                break

    return first_scene or default


def find_latest_video(media_dir: Path) -> Optional[Path]:
    if not media_dir.exists():
        return None

    videos = []
    for ext in ("*.mp4", "*.mov", "*.webm"):
        videos.extend(media_dir.rglob(ext))

    if not videos:
        return None

    return max(videos, key=lambda p: p.stat().st_mtime)


def copy_final_video(video_path: Path, final_video_dir: Path, scene: str) -> Path:
    final_video_dir.mkdir(parents=True, exist_ok=True)

    for old_video in final_video_dir.glob("*"):
        if old_video.is_file() and old_video.suffix.lower() in {".mp4", ".mov", ".webm"}:
            old_video.unlink()

    final_path = final_video_dir / f"{scene}{video_path.suffix.lower()}"
    shutil.copy2(video_path, final_path)
    return final_path


def tail_text(text: str, max_chars: int = 6000) -> str:
    if len(text) <= max_chars:
        return text
    return text[-max_chars:]


def render_manim_for_skill(
    code: str,
    job_dir: str | Path,
    scene_name: Optional[str] = None,
    quality: str = "ql",
    transparent: bool = False,
    timeout: int = 300,
    manim_command: Optional[list[str]] = None,
) -> dict[str, Any]:
    """
    Render Manim code generated by an agent and return a structured result.

    Inputs:
    - code: Manim Python source code.
    - job_dir: task directory used for source, output, media, and logs.
    - scene_name: optional Scene class name; auto-detected when omitted.
    - quality: one of ql/qm/qh/qk.
    - transparent: render with alpha channel; Manim usually outputs .mov.

    Output:
    - A JSON-serializable dict suitable for returning directly to the agent.
    """
    if quality not in QUALITY_FLAGS:
        raise ValueError(f"quality must be one of {sorted(QUALITY_FLAGS)}, got {quality!r}")

    if timeout <= 0:
        raise ValueError(f"timeout must be positive, got {timeout!r}")

    job_path = Path(job_dir).resolve()

    if is_inside_skill_install_dir(job_path):
        raise ValueError(
            "job_dir must not be inside a .codex/skills or .opencode/skills installation directory. "
            "Use the runtime job directory, such as sessions/<session-id>/jobs/<job-slug>/segments/001, instead."
        )

    source_dir = job_path / "source"
    output_dir = job_path / "output"
    final_video_dir = output_dir / "video"

    source_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    code_path = source_dir / "generated_scene.py"
    log_path = output_dir / "render.log"
    result_path = output_dir / "render_result.json"

    code_path.write_text(code, encoding="utf-8")

    scene = scene_name or detect_scene_name(code)

    temp_root = Path(tempfile.mkdtemp(prefix="manim_skill_"))
    temp_media_dir = temp_root / "media"
    temp_media_dir.mkdir(parents=True, exist_ok=True)

    cmd = [*(manim_command or manim_command_base()), f"-{quality}", "--media_dir", str(temp_media_dir)]

    if transparent:
        cmd.append("-t")

    cmd.extend([str(code_path), scene])

    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"

    start_time = time.time()

    try:
        process = subprocess.run(
            cmd,
            cwd=str(job_path),
            env=env,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
        )

        render_log = process.stdout or ""
        log_path.write_text(render_log, encoding="utf-8")

        rendered_video_path = find_latest_video(temp_media_dir)
        final_video_path = None

        if process.returncode == 0 and rendered_video_path is not None:
            final_video_path = copy_final_video(rendered_video_path, final_video_dir, scene)

        success = final_video_path is not None

        result = {
            "success": success,
            "scene_name": scene,
            "return_code": process.returncode,
            "command": cmd,
            "job_dir": str(job_path),
            "code_path": str(code_path),
            "output_dir": str(output_dir),
            "media_dir": str(final_video_dir),
            "video_path": str(final_video_path) if final_video_path else None,
            "log_path": str(log_path),
            "render_log_tail": tail_text(render_log),
            "elapsed_seconds": round(time.time() - start_time, 2),
        }

        if not success:
            result["error"] = "Manim render failed or no video file generated."

    except subprocess.TimeoutExpired as e:
        render_log = e.stdout or ""
        if isinstance(render_log, bytes):
            render_log = render_log.decode("utf-8", errors="replace")

        log_path.write_text(render_log, encoding="utf-8")

        result = {
            "success": False,
            "error": f"Manim render timeout after {timeout} seconds.",
            "scene_name": scene,
            "command": cmd,
            "job_dir": str(job_path),
            "code_path": str(code_path),
            "output_dir": str(output_dir),
            "media_dir": str(final_video_dir),
            "video_path": None,
            "log_path": str(log_path),
            "render_log_tail": tail_text(render_log),
            "elapsed_seconds": round(time.time() - start_time, 2),
        }

    except Exception as e:
        err = traceback.format_exc()
        log_path.write_text(err, encoding="utf-8")

        result = {
            "success": False,
            "error": str(e),
            "traceback": tail_text(err),
            "scene_name": scene,
            "command": cmd,
            "job_dir": str(job_path),
            "code_path": str(code_path),
            "output_dir": str(output_dir),
            "media_dir": str(final_video_dir),
            "video_path": None,
            "log_path": str(log_path),
            "elapsed_seconds": round(time.time() - start_time, 2),
        }
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)

    result["result_path"] = str(result_path)

    import json

    result_path.write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    return result


def main():
    import argparse
    import json

    parser = argparse.ArgumentParser(description="Render Manim code for this skill.")

    parser.add_argument(
        "--job-dir",
        required=True,
        help="Job directory used to save source, output, media, and logs.",
    )

    parser.add_argument(
        "--code-file",
        required=True,
        help="Path to the generated Manim Python code file.",
    )

    parser.add_argument(
        "--scene-name",
        default=None,
        help="Manim Scene class name. If omitted, auto-detect from code.",
    )

    parser.add_argument(
        "--quality",
        default="ql",
        choices=sorted(QUALITY_FLAGS),
        help="Manim render quality. Default: ql.",
    )

    parser.add_argument(
        "--transparent",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Render transparent background. Usually outputs .mov. Default: false.",
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Render timeout seconds. Default: 300.",
    )

    parser.add_argument(
        "--manim-command",
        default=None,
        help="Optional Manim command to run, such as a full path to manim.exe. Default: auto-detect.",
    )

    args = parser.parse_args()

    code_path = Path(args.code_file).resolve()

    if not code_path.exists():
        result = {
            "success": False,
            "error": f"code file not found: {code_path}",
            "code_path": str(code_path),
        }
        print(json.dumps(result, ensure_ascii=False, indent=2))
        raise SystemExit(1)

    code = code_path.read_text(encoding="utf-8", errors="replace")

    result = render_manim_for_skill(
        code=code,
        job_dir=args.job_dir,
        scene_name=args.scene_name,
        quality=args.quality,
        transparent=args.transparent,
        timeout=args.timeout,
        manim_command=parse_command(args.manim_command),
    )

    print(json.dumps(result, ensure_ascii=False, indent=2))

    if not result.get("success"):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
